### ISSUE TITLE
Problem about build a class "Why"

### ISSUE THREAD

**Issue by Vihagle** [DataCanvasIO/YLearn#30]
<em>Please make sure that this is a bug. </em>

**System information**
- OS Platform and Distribution (e.g., CentOS 7.6):
- Python version:3.9.12
- YLearn version:0.1.2
- Other Python packages(run `pip list`):

**Describe the current behavior**

- I build a class "Why()", and input a estimate instance "t = TLearner(model=xgb.XGBRegressor())", but when I fit and then get bug, show as below:
`t = TLearner(model=xgb.XGBRegressor())`
`why = Why(estimator = t,random_state=2022)`
`why.fit(data, outcome, treatment = treatment)`

**Describe the expected behavior**
- It should run successfully

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Jupyter notebook.

**Are you willing to submit PR?(Yes/No)**
- Yes

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. 
If including tracebacks, please include the full traceback. Large logs and files 
should be attached.

**Comment by lixfz** [comment]
This issue was fixed with commit https://github.com/DataCanvasIO/YLearn/commit/e1d47006c56daff455bae5e58f8636584f804e22 .

As a workaround before we release next version,  create `Why` instance with code below:

```python
why=Why(estimator='meta_leaner',
    estimator_options=dict(leaner='t',model=xgb.XGBRegressor())
```
