### ISSUE TITLE
Problem about plotting policy tree

### ISSUE THREAD

**Issue by Vihagle** [DataCanvasIO/YLearn#32]
<em>Please make sure that this is a bug. </em>

**System information**
- OS Platform and Distribution (e.g., CentOS 7.6):Win10
- Python version:3.9.12
- YLearn version:0.1.2
- Other Python packages(run `pip list`):

**Describe the current behavior**
- I wanna use API `why.plot_policy_tree()`, and I specify control, like:
`why.plot_policy_tree(whatif_data,  max_depth=2, treatment = 'CRIM',control = 3)`
- Then I  get bug which show as below:
`invalid index to scalar variable`

**Describe the expected behavior**
- It should output the different leaf nodes and causal effect value compared to control value I specify.(like I specify control = 3) 

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Jupyter notebook.

**Are you willing to submit PR?(Yes/No)**
- Yes

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. 
If including tracebacks, please include the full traceback. Large logs and files 
should be attached.

**Comment by lixfz** [comment]
Can you "Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Jupyter notebook."?

**Comment by Vihagle** [comment]
OK, I share a notebook use open source dataset like "Boston House Price", please check~



***@***.***
 
From: LiXuefeng
Date: 2022-08-03 13:19
To: DataCanvasIO/YLearn
CC: Vihagle; Author
Subject: Re: [DataCanvasIO/YLearn] Problem about plotting policy tree (Issue #32)
Can you "Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Jupyter notebook."?

**Comment by lixfz** [comment]
But, I can not find the notebook you shared here.  Upload it as a attachment from github website please.

**Comment by Vihagle** [comment]
Sry, I just send a email with attachment, maybe I can send notebook to your email `lixf@sovon.net`

**Comment by lixfz** [comment]
Thank you for your notebook, I reproduced the issue.

**Comment by lixfz** [comment]
I fix this issue in the main branch.
At current timestamp, call plot_policy_tree with `control=None` please.

**Comment by Vihagle** [comment]
OK, looking forward to seeing the next version of `ylearn` update~
