### ISSUE TITLE
How to use customed causal graph when calling Why.fit() ?

### ISSUE THREAD

**Issue by FatQiang** [DataCanvasIO/YLearn#40]
This template is for miscellaneous issues not covered by the other issue categories.

**Comment by lixfz** [comment]
If the causal graph is known， please pass `adjustment`/`covariate`/`instrument` options when calling `Why.fit`

**Comment by Lllllp93** [comment]
> If the causal graph is known， please pass `adjustment`/`covariate`/`instrument` options when calling `Why.fit`

So is it means that `YLearn` doesn't support identifying the `instrument'/'covariate' variables automatically by a causal graph provided by the user?

**Comment by lixfz** [comment]
`Why` does not accept  causal graph  as `fit`'s argument.  But one can use ylearn `CausalModel` to identify adjustment/instrument from the known causal graph, see [example_usages/test_model.ipynb](https://github.com/DataCanvasIO/YLearn/blob/main/example_usages/test_model.ipynb) for more details.
