### ISSUE TITLE
Dependency on turtle

### ISSUE THREAD

**Issue by nodiz** [DataCanvasIO/YLearn#48]
Why does model.py use turtle.clone instead of deepcopy to clone the estimator?

I'm asking because removing the dependency on turtle would be nice, as turtle requires tkinter and tkinter is difficult to have in some development environment (databricks to make an example)

**Comment by BochenLv** [comment]
Hi,

Thanks for this great suggestion! We replace turtle.clone with deepcopy in model.py. The dependency on turtle is now completely removed.
